/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author ACER
 */
import Model.Activity;
import Model.DailyEntry;
import Model.Food;
import Model.User;
import Util.FileStorageUtil;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class DailyCaloriePanel extends JPanel {

    private User currentUser;
    private List<User> allUsers;
    private MainAppFrame parentFrame;
    private DailyEntry currentDailyEntry;
    
    public DailyCaloriePanel(User user, List<User> allUsers, MainAppFrame parentFrame) {
        this.currentUser = user;
        this.allUsers = allUsers;
        this.parentFrame = parentFrame;
        initComponents();
        lblWelcomeUser.setText("Halo, " + currentUser.getNama() + "!");
        lblCurrentDate.setText("Tanggal: " + LocalDate.now().format(DateTimeFormatter.ofPattern("dd MMMM yy")));
        loadOrCreateDailyEntry();
    }
    
    public void setCurrentUser(User user) {
        this.currentUser = user;
        lblWelcomeUser.setText("Halo, " + currentUser.getNama() + "!");
    }
    
    public void loadOrCreateDailyEntry() {
        LocalDate today = LocalDate.now();
        Optional<DailyEntry> optionalEntry = currentUser.getDailyEntries().stream()
            .filter(e -> e.getTanggal().isEqual(today))
            .findFirst();

        if (optionalEntry.isPresent()) {
            currentDailyEntry = optionalEntry.get();
            txtKaloriAwal.setText(String.valueOf(currentDailyEntry.getKaloriAwal()));
            txtKaloriAwal.setEditable(false);
            btnSetKaloriAwal.setEnabled(false);
            lblTotalKalori.setText(String.valueOf(currentDailyEntry.getTotalKaloriSaatIni()));

            if (currentDailyEntry.isStatusSelesai()) {
                disableInputFields();
                //JOptionPane.showMessageDialog(this, "Data kalori hari ini sudah direkap dan tidak dapat diubah.", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                enableInputFields();
            }
        } else {
            currentDailyEntry = new DailyEntry(today, 0);
            currentUser.getDailyEntries().add(currentDailyEntry);
            lblTotalKalori.setText("0");
            enableInputFields();
        }
        updateAndSaveData();
    }
    
    private void updateAndSaveData() {
        lblTotalKalori.setText(String.valueOf(currentDailyEntry.getTotalKaloriSaatIni()));
        FileStorageUtil.saveAllUsers(allUsers);
    }
    
    private void disableInputFields() {
        txtKaloriAwal.setEditable(false);
        btnSetKaloriAwal.setEnabled(false);
        txtNamaMakanan.setEditable(false);
        txtKaloriTambahan.setEditable(false);
        btnAddMakanan.setEnabled(false);
        txtNamaAktivitas.setEditable(false);
        txtKaloriTerbakar.setEditable(false);
        btnAddAktivitas.setEnabled(false);
        btnRekapHarian.setEnabled(false);
    }
    
    private void enableInputFields() {
        txtKaloriAwal.setEditable(currentDailyEntry.getKaloriAwal() == 0);
        btnSetKaloriAwal.setEnabled(currentDailyEntry.getKaloriAwal() == 0);

        txtNamaMakanan.setEditable(true);
        txtKaloriTambahan.setEditable(true);
        btnAddMakanan.setEnabled(true);
        txtNamaAktivitas.setEditable(true);
        txtKaloriTerbakar.setEditable(true);
        btnAddAktivitas.setEnabled(true);
        btnRekapHarian.setEnabled(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        lblWelcomeUser = new javax.swing.JLabel();
        lblCurrentDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtKaloriAwal = new javax.swing.JTextField();
        btnSetKaloriAwal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTotalKalori = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNamaMakanan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtKaloriTambahan = new javax.swing.JTextField();
        btnAddMakanan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNamaAktivitas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtKaloriTerbakar = new javax.swing.JTextField();
        btnAddAktivitas = new javax.swing.JButton();
        btnRekapHarian = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setBackground(new java.awt.Color(51, 51, 51));

        lblWelcomeUser.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeUser.setText("jLabel1");

        lblCurrentDate.setForeground(new java.awt.Color(255, 255, 255));
        lblCurrentDate.setText("jLabel1");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kalori Awal Hari:");

        btnSetKaloriAwal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSetKaloriAwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/lock.png"))); // NOI18N
        btnSetKaloriAwal.setText("Jadikan Kalori Awal");
        btnSetKaloriAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetKaloriAwalActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Kalori Saat Ini:");

        lblTotalKalori.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalKalori.setText("jLabel3");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tambah Kalori");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Nama Makanan/Minuman :");

        txtNamaMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMakananActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Kalori Tambahan                  :");

        btnAddMakanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddMakanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        btnAddMakanan.setText("Tambah Kalori");
        btnAddMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMakananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(112, 112, 112))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(11, 11, 11)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtKaloriTambahan)
                            .addComponent(txtNamaMakanan, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnAddMakanan)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNamaMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtKaloriTambahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnAddMakanan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/download.png"))); // NOI18N
        jLabel3.setText("Input dan Hitung Kalori");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Kurangi Kalori (Aktivitas)");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Kalori Terbakar           :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Nama Aktivitas           :");
        jLabel12.setToolTipText("");

        btnAddAktivitas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddAktivitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        btnAddAktivitas.setText("Tambah Aktivitas");
        btnAddAktivitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAktivitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamaAktivitas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKaloriTerbakar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnAddAktivitas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNamaAktivitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKaloriTerbakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddAktivitas)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        btnRekapHarian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRekapHarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/document.png"))); // NOI18N
        btnRekapHarian.setText("Rekap Data");
        btnRekapHarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRekapHarianActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        btnLogout.setText("Keluar");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblTotalKalori))
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblCurrentDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(lblWelcomeUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(txtKaloriAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSetKaloriAwal))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(61, 61, 61)
                                    .addComponent(btnRekapHarian, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(jLabel3))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWelcomeUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCurrentDate)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKaloriAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetKaloriAwal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalKalori))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRekapHarian)
                    .addComponent(btnLogout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetKaloriAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetKaloriAwalActionPerformed
        if (currentDailyEntry.isStatusSelesai()) {
             JOptionPane.showMessageDialog(this, "Data hari ini sudah direkap.", "Info", JOptionPane.WARNING_MESSAGE);
             return;
        }
        try {
            int kaloriAwal = Integer.parseInt(txtKaloriAwal.getText());
            if (kaloriAwal < 0) {
                JOptionPane.showMessageDialog(this, "Kalori awal tidak boleh negatif.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            currentDailyEntry.setKaloriAwal(kaloriAwal);
            currentDailyEntry.setTotalKaloriSaatIni(kaloriAwal);
            updateAndSaveData();

            txtKaloriAwal.setEditable(false);
            btnSetKaloriAwal.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Kalori awal berhasil diatur.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk kalori awal.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSetKaloriAwalActionPerformed

    private void btnAddMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMakananActionPerformed
        if (currentDailyEntry.isStatusSelesai()) {
             JOptionPane.showMessageDialog(this, "Data hari ini sudah direkap.", "Info", JOptionPane.WARNING_MESSAGE);
             return;
        }
        String namaMakanan = txtNamaMakanan.getText().trim();
        if (namaMakanan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama makanan tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            int kaloriTambahan = Integer.parseInt(txtKaloriTambahan.getText());
            if (kaloriTambahan < 0) {
                JOptionPane.showMessageDialog(this, "Kalori tambahan tidak boleh negatif.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Food food = new Food(namaMakanan, kaloriTambahan);
            currentDailyEntry.addFoodLog(food);
            currentDailyEntry.setTotalKaloriSaatIni(currentDailyEntry.getTotalKaloriSaatIni() + kaloriTambahan);
            updateAndSaveData();

            txtNamaMakanan.setText("");
            txtKaloriTambahan.setText("");
            JOptionPane.showMessageDialog(this, "Kalori dari makanan berhasil ditambahkan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk kalori tambahan.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddMakananActionPerformed

    private void btnAddAktivitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAktivitasActionPerformed
        if (currentDailyEntry.isStatusSelesai()) {
             JOptionPane.showMessageDialog(this, "Data hari ini sudah direkap.", "Info", JOptionPane.WARNING_MESSAGE);
             return;
        }
        String namaAktivitas = txtNamaAktivitas.getText().trim();
        if (namaAktivitas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama aktivitas tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            int kaloriTerbakar = Integer.parseInt(txtKaloriTerbakar.getText());
            if (kaloriTerbakar < 0) {
                JOptionPane.showMessageDialog(this, "Kalori terbakar tidak boleh negatif.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Activity activity = new Activity(namaAktivitas, kaloriTerbakar);
            currentDailyEntry.addActivityLog(activity);
            currentDailyEntry.setTotalKaloriSaatIni(currentDailyEntry.getTotalKaloriSaatIni() - kaloriTerbakar);
            updateAndSaveData();

            txtNamaAktivitas.setText("");
            txtKaloriTerbakar.setText("");
            JOptionPane.showMessageDialog(this, "Kalori dari aktivitas berhasil dikurangi.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk kalori terbakar.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddAktivitasActionPerformed

    private void btnRekapHarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRekapHarianActionPerformed
        if (currentDailyEntry.isStatusSelesai()) {
            JOptionPane.showMessageDialog(this, "Hari ini sudah direkap.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menyelesaikan penghitungan kalori hari ini? Data tidak akan bisa diubah lagi.", "Konfirmasi Rekap", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            currentDailyEntry.setStatusSelesai(true);
            updateAndSaveData();
            disableInputFields();
            JOptionPane.showMessageDialog(this, "Data kalori hari ini berhasil direkap!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRekapHarianActionPerformed

    private void txtNamaMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMakananActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin Keluar?",
                "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            if (parentFrame != null) {
                parentFrame.showLoginPanel();
            }
        }
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAktivitas;
    private javax.swing.JButton btnAddMakanan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRekapHarian;
    private javax.swing.JButton btnSetKaloriAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCurrentDate;
    private javax.swing.JLabel lblTotalKalori;
    private javax.swing.JLabel lblWelcomeUser;
    private javax.swing.JTextField txtKaloriAwal;
    private javax.swing.JTextField txtKaloriTambahan;
    private javax.swing.JTextField txtKaloriTerbakar;
    private javax.swing.JTextField txtNamaAktivitas;
    private javax.swing.JTextField txtNamaMakanan;
    // End of variables declaration//GEN-END:variables
}
