/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author ACER
 */
import Model.User;
import Util.FileStorageUtil;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class MainAppFrame extends javax.swing.JFrame {

    private List<User> allUsers;
    private User currentUser;
    private DailyCaloriePanel dailyPanel;
    private HistoryPanel historyPanel;
    
    public MainAppFrame() {
        initComponents();
        setLocationRelativeTo(null);

        allUsers = FileStorageUtil.loadAllUsers();
        loadUsersToComboBox();

        tabbedPaneMain.setVisible(false);
        pnlLogin.setVisible(true);
    }
    
     public void showLoginPanel() {
        tabbedPaneMain.setVisible(false); 
        pnlLogin.setVisible(true); 
     
        txtNamaUser.setText("");
        loadUsersToComboBox(); 
        
        tabbedPaneMain.removeAll(); 
        currentUser = null;
        dailyPanel = null;
        historyPanel = null;
    }
    
    private void loadUsersToComboBox() {
        DefaultComboBoxModel<User> model = new DefaultComboBoxModel<>();
        if (allUsers.isEmpty()) {
            btnLanjutkan.setEnabled(false);
            btnHapusUser.setEnabled(false);
        } else {
            btnLanjutkan.setEnabled(true);
            btnHapusUser.setEnabled(true);
            for (User user : allUsers) {
                model.addElement(user);
            }
        }
        cmbPilihUser.setModel(model);
        if (allUsers.isEmpty()) {
            cmbPilihUser.setSelectedItem(null);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaUser = new javax.swing.JTextField();
        btnDaftarUser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblInfoID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbPilihUser = new javax.swing.JComboBox<>();
        btnLanjutkan = new javax.swing.JButton();
        btnHapusUser = new javax.swing.JButton();
        tabbedPaneMain = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        pnlLogin.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/calories.png"))); // NOI18N
        jLabel1.setText("Selamat Datang di KaloriKu!");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Pengguna :");

        btnDaftarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        btnDaftarUser.setText("Tambah User");
        btnDaftarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarUserActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Atau Pilih Pengguna Yang Ada : ");

        btnLanjutkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/forward.png"))); // NOI18N
        btnLanjutkan.setText("Lanjutkan");
        btnLanjutkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutkanActionPerformed(evt);
            }
        });

        btnHapusUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnHapusUser.setText("Hapus User");
        btnHapusUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInfoID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnDaftarUser))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLoginLayout.createSequentialGroup()
                                .addComponent(btnHapusUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLanjutkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cmbPilihUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDaftarUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblInfoID))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPilihUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLanjutkan)
                    .addComponent(btnHapusUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusUserActionPerformed
        User userToDelete = (User) cmbPilihUser.getSelectedItem();
        if (userToDelete == null) {
            JOptionPane.showMessageDialog(this, "Pilih pengguna yang ingin dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menghapus pengguna '" + userToDelete.getNama() + "' dan semua datanya?",
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            allUsers.remove(userToDelete);
            FileStorageUtil.saveAllUsers(allUsers);
            JOptionPane.showMessageDialog(this, "Pengguna '" + userToDelete.getNama() + "' berhasil dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            loadUsersToComboBox();
        }
    }//GEN-LAST:event_btnHapusUserActionPerformed

    private void btnLanjutkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutkanActionPerformed
        currentUser = (User) cmbPilihUser.getSelectedItem();
        if (currentUser == null) {
            JOptionPane.showMessageDialog(this, "Pilih pengguna terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        pnlLogin.setVisible(false);

        if (dailyPanel == null) {
            dailyPanel = new DailyCaloriePanel(currentUser, allUsers, this); 
            tabbedPaneMain.addTab("Input & Hitung Kalori", dailyPanel);
        } else {
            dailyPanel.setCurrentUser(currentUser);
            dailyPanel.loadOrCreateDailyEntry();
        }

        if (historyPanel == null) {
            historyPanel = new HistoryPanel(currentUser);
            tabbedPaneMain.addTab("Riwayat Harian", historyPanel);
        } else {
            historyPanel.setCurrentUser(currentUser);
            historyPanel.loadHistoryData();
        }
        
        tabbedPaneMain.setVisible(true);
        tabbedPaneMain.setSelectedIndex(0);

        tabbedPaneMain.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (tabbedPaneMain.getSelectedComponent() == historyPanel) {
                    historyPanel.loadHistoryData();
                }
            }
        });
    }//GEN-LAST:event_btnLanjutkanActionPerformed

    private void btnDaftarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarUserActionPerformed
        String nama = txtNamaUser.getText().trim();
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama pengguna tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean namaExists = allUsers.stream().anyMatch(u -> u.getNama().equalsIgnoreCase(nama));
        if (namaExists) {
            JOptionPane.showMessageDialog(this, "Nama pengguna sudah ada. Silakan gunakan nama lain.", "Error Duplikasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        User newUser = new User(nama);
        allUsers.add(newUser);
        FileStorageUtil.saveAllUsers(allUsers);

        JOptionPane.showMessageDialog(this, "Pengguna '" + nama + "' berhasil didaftarkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        txtNamaUser.setText("");
        loadUsersToComboBox();
    }//GEN-LAST:event_btnDaftarUserActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftarUser;
    private javax.swing.JButton btnHapusUser;
    private javax.swing.JButton btnLanjutkan;
    private javax.swing.JComboBox<User> cmbPilihUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblInfoID;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTabbedPane tabbedPaneMain;
    private javax.swing.JTextField txtNamaUser;
    // End of variables declaration//GEN-END:variables
}
